language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t bpopovska/docker-react .

script:
  - docker run -e CI=true bpopovska/docker-react npm run test -- --coverage
